version: '3.8'

services:
  zk-flow:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - .:/app
      - /app/node_modules # Keep node_modules separate to avoid overriding with empty local folder
    networks:
      - zk-network

networks:
  zk-network:
    driver: bridge
