name: Deploy Next.js App

on:
  push:
    branches:
      - main  # Change this if you're using a different deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Next.js App
        run: npm run build

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/Project/starthack2025  # Change to your project's directory
            git pull origin main  # Pull latest changes
            npm install --legacy-peer-deps  # Install dependencies
            npm run build  # Build the Next.js app
            pm2 restart starthack || pm2 start npm --name "starthack" -- start -- --port 3002
